export const MOVIES_REQUEST = 'MOVIES_REQUEST'
export const MOVIES_SUCCESS = 'MOVIES_SUCCESS'
export const MOVIES_FAILURE = 'MOVIES_FAILURE'

export const MOVIE_REQUEST = 'MOVIE_REQUEST'
export const MOVIE_SUCCESS = 'MOVIE_SUCCESS'
export const MOVIE_FAILURE = 'MOVIE_FAILURE'

export const CREDITS_REQUEST = 'CREDITS_REQUEST'
export const CREDITS_SUCCESS = 'CREDITS_SUCCESS'
export const CREDITS_FAILURE = 'CREDITS_FAILURE'

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST'
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS'
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE'

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'